### PR TITLE
Move PNG assets for rails 4 asset pipeline changes

### PR DESCRIPTION
**Pull request by greinacker**
From http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html, 

> In Rails 4.0, precompiling assets no longer automatically copies non-JS/CSS assets from vendor/assets and lib/assets. Rails application and engine developers should put these assets in app/assets or configure config.assets.precompile.

This commit moves the PNG assets from vendor/assets into app/assets, and makes the gem work with the Rails 4 asset pipeline.

### CODE REVIEW

**Comment by brendon** [comment]
This would still be a handy change. Any chance of getting it merged? :)

**Comment by januszm** [comment]
Guys, please merge this.

**Comment by greinacker** [comment]
This was my PR from a while back; for those still running into this, another option is to switch to Fancybox 2, using this gem:

https://github.com/kyparn/fancybox2-rails

Be sure to read the docs about Fancybox 2 - unlike v1, it's not free for commercial use, but rather has a (very) nominal fee.

**Comment by januszm** [comment]
That's why we should just merge the fix for Rails 4. I've found this fork working without issues (and it's just one commit AFAIR)

    gem 'fancybox-rails', github: 'ilnuryakupov/fancybox-rails'

**Comment by greinacker** [comment]
I don't disagree - I wrote the patch, after all. :)  Just providing an alternative if people want it.

**Comment by chrismytton** [comment]
Hi all, sorry for the ridiculous delay getting this merged! I've merged it as https://github.com/chrismytton/fancybox-rails/commit/bb70978898f641cbf2e705e2102110e1caf21134 as part of https://github.com/chrismytton/fancybox-rails/pull/29 which also updates the tests to run on rails 4. Thanks @greinacker for putting this together and sorry again for the looooong delay! :+1:

**Comment by chrismytton** [comment]
I've just released fancybox-rails v0.3.0 which includes this change. :gem:

**Comment by januszm** [comment]
:dancers:

**Pull request closed without merging**
